### ISSUE TITLE
Single template dosen't work without Fediverse params

### ISSUE THREAD

**Issue by LinkSake** [foxihd/hugo-brewm#4]
Hey!

I just started a blog and began to follow `/exampleSite` to configure it. I found out in that if the Fediverse params are not set it won't work:

```
$ hugo server
Watching for changes in /home/link/Code/manzano/{archetypes,assets,content,data,i18n,layouts,static,themes}
Watching for config changes in /home/link/Code/manzano/hugo.toml, /home/link/Code/manzano/themes/hugo-brewm/config.toml
Start building sites …
hugo v0.143.1 linux/amd64 BuildDate=unknown

Built in 61 ms
Error: error building site: render: failed to render pages: render of "/home/link/Code/manzano/content/es/slide.md" failed: "/home/link/Code/manzano/themes/hugo-brewm/layouts/_default/single.html:45:22": execute of template failed: template: _default/single.html:45:22: executing "main" at <resources.GetRemote>: error calling GetRemote: Get "https://<nil>/api/v1/statuses/%3Cnil%3E": dial tcp: lookup <nil>: no such host
```

What made the project run (I can't say that it fix it for sure, since the images stop showing up lol) is adding the params given in the example, my `hugo.toml` looks like this now:

```toml
## Base URL for the site
baseURL = 'https://linksake.github.io/manzano'
## Site title
title = 'Alejandro Manzano'
## Use hugo-brewm theme
theme = 'hugo-brewm'
## Convert all URLs to absolute URLs
canonifyURLs = false
## Default language for content
defaultContentLanguage = 'es'

[params.comments]
disabled = true
## Comments configuration
## Comment platform selection, currently only 'fediverse' is supported, further options to be determined
# platform = 'fediverse'

## Fediverse integration settings
[params.fediverse]
## Fediverse instance URL
instance = 'example.com'
## Fediverse username
username = 'username'
```

The issue seems to be on `layouts/_default/single.html:45`:

```html
...

{{- define "main" }}
    // All these variables set, no matter if there's an entry on the hugo.toml.
    {{- $instance := or .Params.Fediverse.Host .Params.Fediverse.Instance site.Params.fediverse.instance site.Params.fediverse.host }}
    {{- $user := or .Params.Fediverse.User .Params.Fediverse.Username site.Params.fediverse.username site.Params.fediverse.user }}
    {{- $post := or .Params.Fediverse.post .Params.Fediverse.link }}
    {{- $comments := or .Params.toot .Params.comment }}
    {{- if $comments }}
        {{- $toot := split (replaceRE "^https?://" "" .Params.toot) "/" }}
        {{- $instance = index $toot 0 -}}
        {{- $user = trim (index $toot 1) "@" -}}
        {{- $post = index $toot 2 }}
    {{- end }}
    // This is where it breaks since all the variables are null
    {{- $api := print "https://" $instance "/api/v1/statuses/" $post }}
    {{- $isComment := false }}
    {{- $commentUrl :=  print "https://" $instance "/@" $user "/" $post }}
    {{- $avatar := false }}
    {{- $displayName := false }}
    {{- with resources.GetRemote $api }}
        {{- $data := . | transform.Unmarshal }}
        {{- $isComment = $data.content }}
        {{- $commentUrl = $data.url }}
        {{- $avatar = $data.account.avatar }}
        {{- $displayName = $data.account.display_name }}
    {{- end }}

...
```

Is there support for a fediverse-less blog in the future for this theme or will it always be necessary to have some kind of credentials to use it?
